import Head from "next/head";
import path from "path";
import Banner from "../components/Banner";
import Header from "../components/Header";
import MidCards from "../components/MidCards";
import PlaceCard from "../components/PlaceCard";
import { ExplorePlace, MidCard } from "../typing";
import { LargeCardData } from "../LargeCard";

import LargeCardModal from "../components/LargeCardModal";
import Footer from "../components/Footer";

interface Props {
  ExploreData: ExplorePlace[];
  MidCard: MidCard[];
}

export default function Home({ ExploreData, MidCard }: Props) {
  return (
    <div className={""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <main className="max-w-7xl mx-auto px-8 sm:px-12">
        <section className="pt-6 ">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
          {/* pull some data from server -API Endpoints */}
          <div className="grid  grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 ">
            {ExploreData?.map((data) => (
              <PlaceCard
                key={data.img}
                img={data.img}
                distance={data.distance}
                location={data.location}
              />
            ))}
          </div>
        </section>

        {/* 2 Card Medium card */}
        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {MidCard?.map((item) => (
              <MidCards key={item.img} img={item.img} title={item.title} />
            ))}
          </div>
        </section>
        <div>
          {LargeCardData.map(({ img, title, description, buttonText }) => (
            <LargeCardModal
              key={img}
              title={title}
              description={description}
              buttonText={buttonText}
              img={img}
            />
          ))}
        </div>
        <Footer />
      </main>
    </div>
  );
}
//
export async function getStaticProps() {
  const ExploreData = await (
    await fetch("https://www.jsonkeeper.com/b/4G1G").then()
  ).json();
  const MidCard = await (
    await fetch("https://www.jsonkeeper.com/b/VHHT").then()
  ).json();

  return {
    props: {
      ExploreData,
      MidCard,
    },
  };
}
